#!Dockerfile
FROM python:3

WORKDIR /usr/src/app

ADD ./app /usr/src/app

RUN python -m pip install --upgrade pip
COPY requirements.txt /usr/src/app
RUN pip install -r ./requirements.txt

CMD ["python" , "./Flask/app.py"]
EXPOSE 80


