version: "3"
services:
    db:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: "root"
          MONGO_INITDB_ROOT_PASSWORD: "123456"
        ports: 
            - "27017:27017"
        volumes:
            - "./mongodata:/data/db"

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: "mongodb"
            ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "123456"
            ME_CONFIG_BASICAUTH_USERNAME: "root" 
            ME_CONFIG_BASICAUTH_PASSWORD: "123456" 
        depends_on:
            - db


    python:
        build:
            context: .
            dockerfile: Dockerfile-ETL
        container_name: python
        tty: true
        stdin_open: true
        depends_on:
            - db
        ports:
            - "5000:5000"


    ngrok:
        image: wernight/ngrok
        container_name: chatbot_ngrok
        tty: true
        stdin_open: true
        ports:
        - "4040"
        depends_on:
        - python
        environment:
            NGROK_AUTH: "1uULyPiFliDlsPMe5Xj2xa4SbNy_3pCybnjtXmMpsTHbZiHLW"
            NGROK_PORT: "python:5000"
            NGROK_REGION: "ap"
            NGROK_PROTOCOL: "http"
           

    


